name: querydsl-deploy

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - README.md

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  check_duplicate:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'

  build:
    needs: check_duplicate
    if: ${{ needs.check_duplicate.outputs.should_skip != 'true' || github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Initialize cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_USERNAME: circeo
          GITHUB_PASSWORD: ${{ secrets.GH_DEPLOY_PASSWORD }}
        run: mvn --batch-mode clean deploy -Pquickbuild,jpa,apt --settings deploy/.m2/settings.xml -DskipTests

      - name: Clean up before caching
        run: rm -rf ~/.m2/repository/com/querydsl/
